---
version: "2"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    expose:
      - "3306"
    env_file:
      - .env
  node:
    build: ./docker/node
    links:
      - mysql
    ports:
      - "${PORT}:8080"
    volumes:
      - ".:/usr/src/app"
    environment:
      MYSQL_HOST: mysql
    env_file:
      - .env
