version: "2"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    env_file:
      - .env
  app:
    build: .
    links:
      - mysql
    ports:
      - "${PORT}:8080"
    volumes:
      - ./clients/temp:/usr/src/app/clients/temp
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
    env_file:
      - .env
